# Generated by Django 4.0.2 on 2022-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=100000)),
            ],
        ),
    ]
